import { ProductFrame } from "./ProductFrame";
import { Icon } from "@/components/ui/Icon";

const catTone: Record<string, string> = {
  KYC: "bg-blue-100 text-blue-700",
  Contract: "bg-purple-100 text-purple-700",
  Letter: "bg-indigo-100 text-indigo-700",
  Form16: "bg-emerald-100 text-emerald-700",
};
const rows = [
  { doc: "PAN card", cat: "KYC", who: "Ishita Gandhi", expiry: "-", verified: true },
  { doc: "Appointment letter", cat: "Letter", who: "Rohan Nair", expiry: "-", verified: true },
  { doc: "Contract (FTC)", cat: "Contract", who: "Neel Mishra", expiry: "31 Dec 26", verified: false },
  { doc: "Form 16 · FY25-26", cat: "Form16", who: "Kavya Mehta", expiry: "-", verified: true },
];

export function DocumentsVisual() {
  return (
    <ProductFrame title="NeevHR · Documents · Vault">
      <div className="overflow-hidden rounded-xl border border-line">
        <table className="w-full text-left text-[13px]">
          <thead>
            <tr className="bg-surface-soft text-[10px] uppercase text-muted">
              <th className="px-3 py-2 font-semibold">Document</th>
              <th className="px-3 py-2 font-semibold">Category</th>
              <th className="px-3 py-2 font-semibold">Employee</th>
              <th className="px-3 py-2 font-semibold">Expiry</th>
              <th className="px-3 py-2" />
            </tr>
          </thead>
          <tbody>
            {rows.map((r) => (
              <tr key={r.doc} className="border-t border-line">
                <td className="flex items-center gap-2 px-3 py-2 font-medium text-ink">
                  <Icon name="check" className="hidden" />
                  <span className="grid h-5 w-4 place-items-center rounded-sm bg-red-100 text-[8px] font-bold text-red-600">
                    PDF
                  </span>
                  {r.doc}
                </td>
                <td className="px-3 py-2">
                  <span className={`rounded-md px-1.5 py-0.5 text-[10px] font-semibold ${catTone[r.cat]}`}>{r.cat}</span>
                </td>
                <td className="px-3 py-2 text-body">{r.who}</td>
                <td className={`px-3 py-2 text-xs ${r.expiry !== "-" ? "text-amber-600" : "text-muted"}`}>{r.expiry}</td>
                <td className="px-3 py-2 text-right">
                  {r.verified ? (
                    <span className="inline-flex items-center gap-1 text-[11px] font-semibold text-accent-dark">
                      <Icon name="check" className="h-3.5 w-3.5" /> Verified
                    </span>
                  ) : (
                    <span className="text-[11px] text-muted">Pending</span>
                  )}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <p className="mt-2 text-[11px] text-muted">
        Offer, confirmation and relieving letters generated by mail-merge, filed here and tamper-proof.
      </p>
    </ProductFrame>
  );
}
